version: '3'
services:

    admin:
        container_name: admin-app
        image: arunk2398/adminapplication
        restart: always
        ports:
          - "9000:9000"
        networks:
          - medianet

    customer:
        container_name: customer-app
        image: arunk2398/customerapplication
        restart: always
        ports:
          - "4000:4000"
        networks:
          - medianet

    reverseproxy:
        container_name: nginx-config
        image: arunk2398/nginx-config
        ports:
          - "80:8080"
        networks:
          - medianet

networks:
  medianet:
    driver: bridge